apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.1.1

resources:
  - resources/namespace.yaml

patchesStrategicMerge:
  - patches/argocd-cm.yaml
  - patches/argocd-rbac-cm.yaml
