apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
namespace: argocd-platform
bases: 
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.1.6
resources:
  - resources/namespace.yaml
patchesStrategicMerge:
  - patches/argocd-application-controller-clusterrolebinding.yaml
  - patches/argocd-server-clusterrolebinding.yaml
